### PR TITLE
#149: Workaround for GROUP BY <integer>

### LINKED ISSUE #149: VS Workaround for `GROUP BY <integer>`
## Summary

When users combine integer constants as expressions with `DISTINCT`, the engine pushes down `GROUP BY <integer-constant>`. Exasol interprets this as "group by column number", which yields wrong results. What should happen here is that you get a result with a single group. `GROUP BY TRUE`, `GROUP BY '0'` or any other non-integer constant will work as expected.

Note that some databases interpret this as "group by integer constant". So the behavior is database specific. The reason is that this case is *not covered by the SQL standard*.

Workaround:

The adapter should work around this by turning `GROUP BY <integer-constant>` into `GROUP BY <other-constant>`.

Theoretically that should be done on a db-by-db basis, but that is too much effort, so a general workaround in VSCL and VSCJ should be implemented. This can be overridden in the dialect if there is ever the need.

## Features

- Turns `GROUP BY <integer-constant>` into `GROUP BY <other-constant>`

### PR DESCRIPTION
**Pull request by kaklakariada**
Closes #149

### CODE REVIEW

File: src/main/java/com/exasol/adapter/dialects/rewriting/SqlGenerationVisitor.java [hunk 1]
```diff
@@ -240,11 +242,31 @@ public String visit(final SqlFunctionAggregateListagg sqlFunctionAggregateListag
...
+    /**
+     * Replace an unsupported expression in a {@code GROUP BY} clause with a supported one or return it unchanged.
+     * 
+     * @implNote This replaces numeric literals with their string value as Exasol interprets
+     *           {@code GROUP BY <integer-constant>} as column numbers which was not intended.
+     * 
+     * @param node the original {@code GROUP BY} expression
+     * @return an new, alternative expression or the original expression if no replacement is necessary
+     */
+    private SqlNode replaceGroupByExpression(final SqlNode node) {
```
Comment (redcatbear) [inline src/main/java/com/exasol/adapter/dialects/rewriting/SqlGenerationVisitor.java:260]: I would rename this method to `workaroundGroupByInteger`. Workarounds should be as visible as possible. Makes it easier to later get rid of them, should the actual source of the problem be fixed.

File: doc/changes/changes_11.0.1.md [hunk 2]
```diff
@@ -1,9 +1,21 @@
...
 
 ## Summary
 
+This release fixes an issue with queries using `DISTINCT` or `GROUP BY` with integer constants. Exasol interprets integers in `GROUP BY` clauses as column numbers which could lead to invalid results or the following error:
+
+```
+42000:Wrong column number. Too small value 0 as select list column reference in GROUP BY (smallest possible value is 1)
+```
+
+To fix this, VSCJ now replaces integer constants in `GROUP BY` clauses with a constant string. Please note that `GROUP BY <column-number>` is not affected by this and continues to work as expected.
```
Comment (redcatbear) [inline doc/changes/changes_11.0.1.md:13]:
```suggestion
To fix this, VSCJ now replaces integer constants in `GROUP BY` clauses with a constant string.

Please that you can still safely use `GROUP BY <column-number>` in your original query, since Exasol internally converts this to `GROUP BY "<column-name>"`, so that the virtual schema adapter can tell both situations apart.
```

**Comment by redcatbear** [comment]
Also I would feel better if you invested a little bit extra time into an integration test with Derby (already in the POM).

**Comment by kaklakariada** [comment]
Integration tests with the Exasol require a lot of setup effort in this project. I will add integration tests in https://github.com/exasol/exasol-virtual-schema/issues/108.

**Review by ckunki — CHANGES_REQUESTED** [review]

**Review by redcatbear — APPROVED** [review]

File: doc/changes/changes_11.0.1.md [hunk 3]
```diff
@@ -1,9 +1,23 @@
...
 
 ## Summary
 
+This release fixes an issue with queries using `DISTINCT` with integer constants. The Exasol SQL processor turns `DISTINCT <integer>` into `GROUP BY <integer>` before push-down as an optimization. The adapter must not feed this back as Exasol interprets integers in `GROUP BY` clauses as column numbers which could lead to invalid results or the following error:
+
+```
+42000:Wrong column number. Too small value 0 as select list column reference in GROUP BY (smallest possible value is 1)
+```
+
+To fix this, VSCJ now replaces integer constants in `GROUP BY` clauses with a constant string.
```
[the remark this answers is not in the document]
Comment (kaklakariada) [reply doc/changes/changes_11.0.1.md]: Good catch! ✅

**Review by redcatbear — APPROVED** [review]
