### PR TITLE
Bug/105 check metadata not null

### LINKED ISSUE #104: Update dependencies
## Problem 

We want to update dependencies, in particular, `error-reporting-java`  because it's not possible now to update it in VS dialects, there is some version conflict.

### LINKED ISSUE #105: NullPointerException when an external JDBC driver returns null instead of the ResultSetMetaData instance
## Problem

We don't check if the metadata of the result set is present. So the method `mapResultMetadataToExasolDataTypes` of the `ResultSetMetadataReader` throws a null pointer exception when the ResultSetMetaData is null. This happened in the Sybase dialect.

## Solution

We want to validate the metadata and throw a dedicated exception if it's null.

### PR DESCRIPTION
**Pull request by AnastasiiaSergienko**
Closes #105 
Closes #104

### CODE REVIEW

File: src/main/java/com/exasol/adapter/jdbc/ResultSetMetadataReader.java [hunk 1]
```diff
@@ -102,6 +102,16 @@ private String createColumnDescriptionFromDataTypes(final List<DataType> types)
         return types;
     }
 
+    private void validateMetadata(final ResultSetMetaData metadata) {
+        if (metadata == null) {
+            throw new RemoteMetadataReaderException(ExaError.messageBuilder("E-VS-COM-JDBC-34") //
```
Comment (jakobbraun) [inline src/main/java/com/exasol/adapter/jdbc/ResultSetMetadataReader.java:107]:
```suggestion
            throw new RemoteMetadataReaderException(ExaError.messageBuilder("F-VS-COM-JDBC-34") //
```

If it's a ticket mitigation the user probably can't do anything about it? Then I would use `F`

File: src/test/java/com/exasol/adapter/jdbc/ResultSetMetadataReaderTest.java [hunk 2]
```diff
@@ -58,4 +58,16 @@ void testDescribeColumnThrowsExceptionIfUnsupportedColumnContained() throws SQLE
...
+    @Test
+    void testEmptyMetadata() throws SQLException {
+        when(this.connectionMock.prepareStatement(any())).thenReturn(this.statementMock);
+        final ColumnMetadataReader columnMetadataReader = new BaseColumnMetadataReader(this.connectionMock,
+                AdapterProperties.emptyProperties(), BaseIdentifierConverter.createDefault());
+        final ResultSetMetadataReader metadataReader = new ResultSetMetadataReader(this.connectionMock,
+                columnMetadataReader);
+        final RemoteMetadataReaderException exception = assertThrows(RemoteMetadataReaderException.class,
+                () -> metadataReader.describeColumns("FOOBAR"));
+        assertThat(exception.getMessage(), containsString("E-VS-COM-JDBC-34"));
```
Comment (jakobbraun) [inline src/test/java/com/exasol/adapter/jdbc/ResultSetMetadataReaderTest.java:71]:
```suggestion
        assertThat(exception.getMessage(), containsString("F-VS-COM-JDBC-34"));
```

**Review by jakobbraun — DISMISSED** [review]
