### PR TITLE
#169: Fix validation of TELEMETRY property

### LINKED ISSUE #169: Property TELEMETRY not supported
Creating a VS with property TELEMETRY fails: https://github.com/exasol/oracle-virtual-schema/actions/runs/24730583620/job/72343583166?pr=85

```
CREATE VIRTUAL SCHEMA "ORACLE_VIRTUAL_SCHEMA_0"
USING "SCHEMA_EXASOL"."ADAPTER_SCRIPT_EXASOL" WITH
  SCHEMA_NAME = 'ID1'
  TELEMETRY = 'false'
  CONNECTION_NAME = 'ORACLE_CONNECTION''. Cause: 'VM error: F-UDF-CL-LIB-1126: F-UDF-CL-SL-JAVA-1006: F-UDF-CL-SL-JAVA-1026: 
com.exasol.ExaUDFException: F-UDF-CL-SL-JAVA-1068: Exception during singleCall adapterCall 
com.exasol.adapter.properties.PropertyValidationException: E-VSCJDBC-13: This dialect does not support property 'TELEMETRY'. Please, do not set this property.
```

### PR DESCRIPTION
**Pull request by kaklakariada**
Closes #169

### CODE REVIEW

File: src/test/java/com/exasol/adapter/dialects/AbstractSqlDialectTest.java [hunk 1]
```diff
@@ -185,6 +186,16 @@ private void verifyValidationException(final String property, final String value
                 () -> assertThat(exception.getMessage(), containsString(property)));
     }
 
+    @ParameterizedTest
+    @CsvSource({ "TELEMETRY, true", "TELEMETRY, false", "TELEMETRY, FALSE", "TELEMETRY, off", "TELEMETRY, ''" })
+    void testPropertySupported(final String property, final String value) {
```
Comment (redcatbear) [inline src/test/java/com/exasol/adapter/dialects/AbstractSqlDialectTest.java:191]: Test name is a bit unspecific for such a narrow test case.

**Review by redcatbear — APPROVED** [review]
Small optional finding.
