### PR TITLE
* #75: Restricted amount of mapped tables in the remote schema to 1000.

### LINKED ISSUE #75: Don't allow create virtual schemas when a source schema has more than 1000 tables
## Problem

We want to warn users that it's not a common use case to create Virtual Schemas for s source schema that contains more than 1000 tables. The users should use the TABLE_FILTER property to specify tables. 

## Solution 

Throw an exception when the source schema contains more than 1000 tables and ask users to add TABLE_FILTER. 

We can also add a property that ignores this check in the future.

### PR DESCRIPTION
**Pull request by AnastasiiaSergienko**
Closes #75

### CODE REVIEW

File: src/main/java/com/exasol/adapter/jdbc/BaseTableMetadataReader.java [hunk 1]
```diff
@@ -40,38 +41,60 @@ public BaseTableMetadataReader(final Connection connection, final ColumnMetadata
...
+        do {
+            final String tableName = readTableName(remoteTables);
+            if (tableIsSupported(selectedTables, tableName)) {
+                final TableMetadata tableMetadata = mapTable(remoteTables, tableName);
+                if (tableHasColumns(tableMetadata, tableName)) {
+                    LOGGER.finer(() -> "Read table metadata: " + tableMetadata.describe());
+                    translatedTables.add(tableMetadata);
+                    validateSelectedTablesListSize(selectedTables);
+                }
+            }
```
Comment (redcatbear) [inline src/main/java/com/exasol/adapter/jdbc/BaseTableMetadataReader.java:69]: Extract method.

File: src/main/java/com/exasol/adapter/jdbc/BaseTableMetadataReader.java [hunk 2]
```diff
@@ -40,38 +41,60 @@ public BaseTableMetadataReader(final Connection connection, final ColumnMetadata
...
 
-    protected void mapOrSkipTable(final ResultSet remoteTables, final List<TableMetadata> translatedTables,
-            final List<String> selectedTables) throws SQLException {
-        final String tableName = readTableName(remoteTables);
+    private void validateSelectedTablesListSize(final List<String> selectedTables) {
+        if (selectedTables.size() > DEFAULT_MAX_MAPPED_TABLE_LIST_SIZE) {
+            throw new RemoteMetadataReaderException(
+                    "The size of the list of the selected tables exceeded the default allowed maximum: "
+                            + DEFAULT_MAX_MAPPED_TABLE_LIST_SIZE + ". "
+                            + "Please, use TABLE_FILTER property to define a list of tables you need.");
```
Comment (redcatbear) [inline src/main/java/com/exasol/adapter/jdbc/BaseTableMetadataReader.java:79]:
```suggestion
                            + "Please, use the TABLE_FILTER property to define the list of tables you need.");
```

File: src/main/java/com/exasol/adapter/jdbc/BaseTableMetadataReader.java [hunk 3]
```diff
@@ -84,12 +107,12 @@ protected boolean isTableSelected(final String tableName, final List<String> sel
         return (selectedTables == null) || selectedTables.isEmpty() || selectedTables.contains(tableName);
     }
 
-    protected void mapOrSkipSelectedTable(final ResultSet remoteTables, final List<TableMetadata> translatedTables,
-            final String tableName) throws SQLException {
+    protected boolean tableIsNotInExclusionsList(final String tableName) {
```
Comment (redcatbear) [inline src/main/java/com/exasol/adapter/jdbc/BaseTableMetadataReader.java:110]: Use positive formulation. Negation in names is confusing. Double negation more so!

**Review by redcatbear — CHANGES_REQUESTED** [review]

File: src/main/java/com/exasol/adapter/jdbc/BaseTableMetadataReader.java [hunk 4]
```diff
@@ -40,118 +41,135 @@ public BaseTableMetadataReader(final Connection connection, final ColumnMetadata
...
+    protected void logSkippingUnsupportedTable(final String tableName) {
+        LOGGER.fine(() -> "Skipping unsupported table \"" + tableName + "\" when mapping remote metadata.");
     }
 
-    protected TableMetadata mapTable(final ResultSet table, final String tableName) throws SQLException {
-        final String comment = Optional.ofNullable(readComment(table)).orElse("");
-        final List<ColumnMetadata> columns = this.columnMetadataReader.mapColumns(tableName);
-        final String adapterNotes = DEFAULT_TABLE_ADAPTER_NOTES;
-        return new TableMetadata(adjustIdentifierCase(tableName), adapterNotes, columns, comment);
+    private boolean tableIsSelected(final List<String> selectedTables, final String tableName) {
```
Comment (redcatbear) [inline src/main/java/com/exasol/adapter/jdbc/BaseTableMetadataReader.java:138]:
```suggestion
    private boolean isTableSelected(final List<String> selectedTables, final String tableName) {
```

**Review by redcatbear — APPROVED** [review]
