### PR TITLE
#20: Refactored ColumnAdapterNotes.

### LINKED ISSUE #20: Refactor ColumnAdapterNotes class
## Problem

ColumnAdapterNotes class needs refactoring. The column name is passed just to have something for the exception messages. Seems like unnecessary detail disclosure at this point.

### PR DESCRIPTION
**Pull request by redcatbear**
Closes #20.

### CODE REVIEW

File: src/main/java/com/exasol/adapter/adapternotes/ColumnAdapterNotes.java [hunk 1]
```diff
@@ -2,108 +2,45 @@
...
         this.jdbcDataType = jdbcDataType;
-        this.typeName = typeName;
     }
 
     /**
      * Get JDBC data type.
-     * 
-     * @return JDBC data type as an int
+     *
+     * @return JDBC data type as an number
```
Comment (AnastasiiaSergienko) [inline src/main/java/com/exasol/adapter/adapternotes/ColumnAdapterNotes.java]:
```suggestion
     * @return JDBC data type as a number
```

File: src/test/java/com/exasol/adapter/adapternotes/ColumnAdapterNotesJsonConverterTest.java [hunk 2]
```diff
@@ -0,0 +1,56 @@
...
+        JSONAssert.assertEquals("{\"" + JDBC_DATA_TYPE + "\":" + expectedType + "}",
+                this.converter.convertToJson(adapterNotes), false);
+    }
+
+    @Test
+    void testConvertFromJsonToColumnAdapterNotes() throws AdapterException {
+        final int expectedType = Types.VARCHAR;
+        final String adapterNotesAsJson = "{\"" + JDBC_DATA_TYPE + "\":" + expectedType + "}";
+        final ColumnAdapterNotes expectedAdapterNotes = new ColumnAdapterNotes(expectedType);
+        assertThat(this.converter.convertFromJsonToColumnAdapterNotes(adapterNotesAsJson, "C1"),
```
Comment (AnastasiiaSergienko) [inline src/test/java/com/exasol/adapter/adapternotes/ColumnAdapterNotesJsonConverterTest.java]: We usually use JSONAssert.assertEquals, don't we?

Comment (redcatbear) [reply src/test/java/com/exasol/adapter/adapternotes/ColumnAdapterNotesJsonConverterTest.java]: Depends on the direction. This is reverse (i.e. deserialization). JSONAssert does not help here.
