### PR TITLE
#69: Fixed wrong error message

### LINKED ISSUE #69: Wrong error message generated by validateCastNumberToDecimalProperty
`validateCastNumberToDecimalProperty` claims the correct format is `<precision>.<scale>` but `<precision>,<scale>` is correct.

### PR DESCRIPTION
**Pull request by jakobbraun**
Closes #69

### CODE REVIEW

File: src/main/java/com/exasol/adapter/dialects/AbstractSqlDialect.java [hunk 1]
```diff
@@ -14,7 +14,11 @@
 import com.exasol.adapter.jdbc.ConnectionFactory;
 import com.exasol.adapter.jdbc.RemoteMetadataReader;
 import com.exasol.adapter.metadata.SchemaMetadata;
-import com.exasol.adapter.sql.*;
+import com.exasol.adapter.sql.AggregateFunction;
+import com.exasol.adapter.sql.ScalarFunction;
+import com.exasol.adapter.sql.SqlNodeVisitor;
+import com.exasol.adapter.sql.SqlStatement;
```
Comment (chiaradiamarcelo) [inline src/main/java/com/exasol/adapter/dialects/AbstractSqlDialect.java:20]: I think you have a problem with the formatter here. This should compress to a single import as it was before

**Review by chiaradiamarcelo — COMMENTED** [review]
Looks good to merge once you fixed the imports

File: src/main/java/com/exasol/adapter/dialects/AbstractSqlDialect.java (hunk 1 above)
Comment (jakobbraun) [reply src/main/java/com/exasol/adapter/dialects/AbstractSqlDialect.java:20]: I formated again using the latest configuration. Seems like it is currently configured like that

**Review by chiaradiamarcelo — APPROVED** [review]
