### PR TITLE
* #92: Fixed base classes of QueryRewriter.

### LINKED ISSUE #92: Fix base classes of QueryRewriter

### PR DESCRIPTION
**Pull request by AnastasiiaSergienko**
Closes #92

### CODE REVIEW

File: src/main/java/com/exasol/adapter/dialects/rewriting/ImportIntoTemporaryTableQueryRewriter.java [hunk 1]
```diff
@@ -7,25 +7,43 @@
...
+     * Construct a new instance of {@link ImportIntoTemporaryTableQueryRewriter}.
      *
      * @param dialect              dialect
      * @param remoteMetadataReader remote metadata reader
      * @param connectionFactory    factory for the JDBC connection to remote data source
      */
-    public ImportIntoQueryRewriter(final SqlDialect dialect, final RemoteMetadataReader remoteMetadataReader,
-            final ConnectionFactory connectionFactory) {
+    public ImportIntoTemporaryTableQueryRewriter(final SqlDialect dialect,
+            final RemoteMetadataReader remoteMetadataReader, final ConnectionFactory connectionFactory) {
```
Comment (chiaradiamarcelo) [inline src/main/java/com/exasol/adapter/dialects/rewriting/ImportIntoTemporaryTableQueryRewriter.java:27]: this constructor should call the other one. Like
```
 public ImportIntoTemporaryTableQueryRewriter(final SqlDialect dialect,
            final RemoteMetadataReader remoteMetadataReader, final ConnectionFactory connectionFactory) {
        this(dialect, remoteMetadataReader, connectionFactory, new BaseConnectionDefinitionBuilder());
    }
```

File: src/test/java/com/exasol/adapter/dialects/rewriting/ImportIntoQueryRewriterTest.java [hunk 2]
```diff
@@ -41,6 +41,6 @@ private QueryRewriter getQueryRewriter(final ConnectionFactory connectionFactory
             final AdapterProperties properties) {
         final SqlDialect dialect = new DummySqlDialect(connectionFactory, properties);
         final BaseRemoteMetadataReader metadataReader = new BaseRemoteMetadataReader(connection, properties);
-        return new ImportIntoQueryRewriter(dialect, metadataReader, connectionFactory);
+        return new ImportIntoTemporaryTableQueryRewriter(dialect, metadataReader, connectionFactory);
```
Comment (chiaradiamarcelo) [inline src/test/java/com/exasol/adapter/dialects/rewriting/ImportIntoQueryRewriterTest.java:44]: Please add also a test case using a custom `ConnectionDefinitionBuilder`

Comment (chiaradiamarcelo) [reply src/test/java/com/exasol/adapter/dialects/rewriting/ImportIntoQueryRewriterTest.java:44]: The test class name should be `ImportIntoTemporaryTableQueryRewritertest`.

File: src/main/java/com/exasol/adapter/dialects/rewriting/ImportFromJDBCQueryRewriter.java [hunk 3]
```diff
@@ -20,9 +21,21 @@ public ImportFromJDBCQueryRewriter(final SqlDialect dialect, final RemoteMetadat
         super(dialect, remoteMetadataReader, new BaseConnectionDefinitionBuilder());
```
Comment (chiaradiamarcelo) [inline src/main/java/com/exasol/adapter/dialects/rewriting/ImportFromJDBCQueryRewriter.java:21]: this constructor should call the other one. Like
```
 public ImportFromJDBCQueryRewriter(final SqlDialect dialect,
            final RemoteMetadataReader remoteMetadataReader) {
        this(dialect, remoteMetadataReader, new BaseConnectionDefinitionBuilder());
    }
```

**Review by chiaradiamarcelo — APPROVED** [review]
