### PR TITLE
#73: Refactored table metadata reading with filtered tables

### LINKED ISSUE #73: Add dedicated method in `TableMetadataReader` API to map all tables
ATM `TableMetadataReader` provides a `public List<TableMetadata> mapTables(ResultSet remoteTables, List<String> selectedTables) throws SQLException;`, which is counter intuitive as passing an empty list of `selectedTables` means `all tables`.

We should add another dedicated method for it.

### PR DESCRIPTION
**Pull request by chiaradiamarcelo**
Closes #73.

### CODE REVIEW

File: src/main/java/com/exasol/adapter/jdbc/BaseTableMetadataReader.java [hunk 1]
```diff
@@ -141,32 +139,25 @@ protected void logSkippingUnsupportedTable(final String tableName) {
         LOGGER.fine(() -> "Skipping unsupported table \"" + tableName + "\" when mapping remote metadata.");
     }
 
-    private boolean isTableSelected(final List<String> selectedTables, final String tableName) {
-        if (checkIfTableIsSelected(tableName, selectedTables)) {
-            return isTableIncludedByFilter(tableName);
+    private boolean isFilteredTable(final List<String> filteredTables, final String tableName) {
+        if (isFilteredByProperties(tableName) && isFiltered(tableName, filteredTables)) {
```
Comment (AnastasiiaSergienko) [inline src/main/java/com/exasol/adapter/jdbc/BaseTableMetadataReader.java:143]: If we group the checks like that we lose an opportunity to log if the table was filtered by request parameters or user filter. Do you think i's fine to have only one log message?
If we keep only one message, I suggest to improve the message and write that "a table was filtered out by request properties OR a user filter" or something like this

**Review by AnastasiiaSergienko — APPROVED** [review]
:+1:
